# -*- coding: utf-8 -*-
"""add two number Ayu pujiastuti.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oOe8jMS21wbVK5VxIP_MPh28Mb876pFF

#Ayu pujiastuti leetcode twosum
"""

l1 = [2,4,3] 
l2 = [5,6,4]

class Solution:
    def addTwoNumbers(self, l1, l2):
        a=str(l1.val); b= str(l2.val)
        next= l1.next
        while next:
          a=str(next.val)+a
          next= next.next
        next= l2.next
        while next:
          b= str(next.val)+b
          next= next.next
          
        c= str(int(a)+int(b))
        i= len(c)-1
        l3= ListNode(int(c[i]))
        next= l3
        while i:          
          i-=1
          ch= int(c[i])
          if next != None:
            next.next= ListNode(ch)          
            next= next.next
        return l3