# -*- coding: utf-8 -*-
"""Program for crawling multiple web pages.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oOe8jMS21wbVK5VxIP_MPh28Mb876pFF

#Ayu pujiastuti leetcode twosum
"""

import requests
from bs4 import BeautifulSoup

url = 'https://www.goodreads.com/search?utf8=%E2%9C%93&q=j.s+khairen&search_type=books'

r = requests.get(url)

requests = r.content

soup = BeautifulSoup(requests, 'html.parser')

title = soup.findAll('a', attrs={'class':'bookTitle'})
author = soup.findAll('a', attrs={'class':'authorName'})

count = 0
for x in range(0, len(title)):
    count += 1
    print("{0}. {1}\n   -{2}"
    .format(count, title[x].text.strip(), author[x].text.strip()))